name: Generate and Deploy Presentations

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Generate presentations
        run: node src/generatePresentations.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./presentations

      - name: Print GitHub Pages URL
        run: |
          echo "Presentation is live at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
